# Generated by Django 4.0.3 on 2022-04-18 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=264)),
                ('middle_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('street', models.CharField(max_length=264)),
                ('state', models.CharField(max_length=264)),
                ('city', models.CharField(max_length=264)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.customerdetail')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
