# Generated by Django 4.0.3 on 2022-04-15 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_medicine_logs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_logs',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
