# Generated by Django 4.0.3 on 2022-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_medicine_logs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_logs',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
