# Generated by Django 4.0.3 on 2022-04-18 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_itemmain_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0005_alter_medicine_logs_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='CustomerDetail',
        ),
        migrations.RenameModel(
            old_name='Medicine_Logs',
            new_name='Medicine_Log',
        ),
    ]
