# Generated by Django 4.0.3 on 2022-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_itemmain_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmain',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
