# Generated by Django 4.0.3 on 2022-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_usercart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmain',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
